version: '3.6'

services:
  web:
    environment:
      - TZ=Europe/Berlin
      - TYPO3_INSTALL_DB_USER=db
      - TYPO3_INSTALL_DB_PASSWORD=db
      - TYPO3_INSTALL_DB_HOST=db
      - TYPO3_INSTALL_DB_PORT=3306
      - TYPO3_INSTALL_DB_UNIX_SOCKET=
      - TYPO3_INSTALL_DB_USE_EXISTING=1
      - TYPO3_INSTALL_DB_DBNAME=db
      - TYPO3_INSTALL_ADMIN_USER=admin
      - TYPO3_INSTALL_ADMIN_PASSWORD=password
      - TYPO3_INSTALL_SITE_NAME=$DDEV_SITENAME
      - TYPO3_INSTALL_SITE_SETUP_TYPE=no
      - TYPO3_HOST=${DDEV_SITENAME}.ddev.local
  db:
    environment:
      - TZ=Europe/Berlin
